### ISSUE TITLE
Loading Error

### ISSUE THREAD

**Issue by madtomic** [neolumia/vault#9]
[14:05:11 ERROR]: Could not load 'plugins\vault-core-1.6.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bstats/Metrics$CustomChart
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:307) [patched_1.12.2.jar:git-Paper-1274]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:225) [patched_1.12.2.jar:git-Paper-1274]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1274]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: org/bstats/Metrics$CustomChart
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1274]
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.bstats.Metrics$CustomChart
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:90) ~[patched_1.12.2.jar:git-Paper-1274]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:68) ~[patched_1.12.2.jar:git-Paper-1274]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127) ~[patched_1.12.2.jar:git-Paper-1274]
        ... 6 more

**Comment by conreptio** [comment]
Please use the right file: "vault-1.6.2-shaded.jar" instead of "vault-core-1.6.2.jar"
